name: doc_display
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
  provider: ^6.0.2
  clipboard: ^0.1.3
  window_manager: ^0.2.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  mqtt_client: ^9.6.5
  short_uuids: ^2.0.0
  darq: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
