name: doc_display
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
  provider: ^6.0.2
  clipboard: ^0.1.3
  window_manager: ^0.2.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  mqtt_client: ^9.6.5
  short_uuids: ^2.0.0
  darq: ^1.1.1
  pdf: ^3.7.3
  printing: ^5.7.5
  dart_vlc:
    git: 
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master

dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
      path: ffi
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
